version: '3'
services:
    mysql:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "15432:5432"
        environment:
          - MYSQL_ROOT_PASSWORD=password
    java:
        image: amazoncorretto:8u265
        volumes:
            - ./project:/project
        ports:
            - "18080:8080"
        working_dir: "/project"
        command: [ "sleep", "infinity" ]
        environment:
          - MYSQL_HOST=mysql
          - MYSQL_USER=root
          - MYSQL_PASSWORD=password

